### ISSUE TITLE
Problem with coding declaration on Windows

### ISSUE THREAD

**Issue by sbaumeister** [winterTTr/ace-jump-mode#17] opened 2012-10-22 15:15 UTC
I'm using el-get to install ace-jump-mode on Windows. There, git saves the file ace-jump-mode.el with DOS style line endings. As the coding declaration of the file is

```
-*- coding: utf-8-unix -*-
```

the following error is displayed, when the file is opened (e.g. by el-get for generating the *.elc file):

```
Local variables entry is missing the suffix
```

To fix the error change the declaration to:

```
-*- coding: utf-8 -*-
```

Possible?

**Comment by winterTTr** [comment] 2012-11-16 06:22
Sorry for the late response, recent is kinda busy life :-)
I tried to reproduce this problem, but now it does not exist.
I guess, you may download some previous version of ace jump mode, which I remember I have been met the similar problem before, but I have fixed it.

So try to download the latest version of ace jump mode ( using el-get? I am not familiar with it, but I guess it should support update).
That's should fix the problem.

**Comment by jschaf** [comment] 2013-05-17 03:52
I have the exact same issue.  Here's part of my backtrace.  Git is cloning the file with DOS line endings, but the file variable in acejump is set to utf-8-unix.  There's 2 solutions I see:
1. Get rid of the coding declaration, Emacs will figure it out anyway.
2. Change the declaration to utf-8

```
 error("Local variables entry is missing the suffix")
  hack-local-variables()
  autoload-find-file("ace-jump-mode/ace-jump-mode.el")
```

**Comment by winterTTr** [comment] 2013-05-17 05:58
Please check the configuration of your windows git.

> git config core.autocrlf

Mine is false, which means when git checkout the text file, it will not automatically convert that file format to dos line ending.

If your is true, that should be the problem.
So you may consider to change this config to fix the problem, or you change this config to the ace jump only local repository, please have a try. :-)

**Comment by jschaf** [comment] 2013-05-17 20:58
That would fix the issue, but I'm sure other people will eventually run into the same problem.

How about marking the git repository to only use Unix line endings.  This makes sense since we're declaring the file to use Unix style line endings anyway.  From [Github's Dealing with Line Endings](https://help.github.com/articles/dealing-with-line-endings), you'd create a .gitattributes file with the following line

```
* text eol=lf
```

This overrides the user's config of `core.autocrlf` so the issue should disappear.

**Comment by winterTTr** [comment] 2013-05-18 02:00
@jschaf 
I have add the gitattribute file to keep unix style format and test the check out files when autocrlf is true, everything goes well.
Thanks very much for your suggestion

**Comment by winterTTr** [comment] 2013-05-18 02:01
So I think we can close this problem

**Closed as completed by winterTTr** 2013-05-18 02:01 UTC
